version: '3.8'

services:
  pitch-perfect:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pitch-perfect-app
    ports:
      - "3000:80"
    restart: unless-stopped
    networks:
      - pitch-perfect-network
    environment:
      - NODE_ENV=production
    volumes:
      # Optional: Mount for development (comment out for production)
      # - ./build:/usr/share/nginx/html:ro
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  pitch-perfect-network:
    driver: bridge